exports.ERR_MODULE_DOWNLOAD_ERROR = 'ERR_MODULE_DOWNLOAD_ERROR';
exports.ERR_MODULE_INSTALLED = 'ERR_MODULE_INSTALLED';
exports.ERR_MODULE_NOT_FOUND = 'ERR_MODULE_NOT_FOUND';
exports.ERR_MODULE_NOT_INSTALLED = 'ERR_MODULE_NOT_INSTALLED';
exports.ERR_MODULE_REMOVE_FAILED = 'ERR_MODULE_REMOVE_FAILED';
exports.ERR_THEME_ALREADY_ACTIVE = 'ERR_THEME_ALREADY_ACTIVE';
